trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  NUGET_FOLDER_NAME: nupkgs
  PRERELEASE_SUFFIX: $(Build.BuildId)
  ARTIFACTS_STAGING_DIR: $(Build.ArtifactStagingDirectory)/$(NUGET_FOLDER_NAME)

stages:
- stage: CI
  jobs:
  - job: Build
    steps:
    - script: echo $(NUGET_FOLDER_NAME) $(PRERELEASE_SUFFIX)
    - task: NuGetAuthenticate@0
    - script: dotnet restore --no-cache --force
    - script: dotnet build --configuration Release --no-restore
    - script: dotnet vstest test/*UnitTests/bin/Release/**/*UnitTests.dll
    - script: dotnet pack *.sln --configuration Release --output $(NUGET_FOLDER_NAME)
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    - script: dotnet pack *.sln --configuration Release --output $(NUGET_FOLDER_NAME) --version-suffix $(PRERELEASE_SUFFIX) --include-source --include-symbols -p:SymbolPackageFormat=snupkg
      condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
    - script: mkdir $(ARTIFACTS_STAGING_DIR)
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(ARTIFACTS_STAGING_DIR)
        artifactName: MyBuildOutputs
  - job: Publish
    steps:
    - task: DownloadBuildArtifacts@0
    - script: ls
