trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

stages:
- stage: Build
  jobs:
  - job: Restore
    steps:
    - task: NuGetAuthenticate@0
    - script: dotnet restore --no-cache --force
  - job: Build
    steps:
    - script: dotnet build --configuration Release --no-restore
  - job: Tests
    steps:
    - script: dotnet vstest test/*Tests/bin/Release/**/*Tests.dll
- stage: Package
  jobs:
  - job: Pack
    steps:
    - script: echo TODO pack